services:
  mlflow:
    profiles: ["cookbot"]
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5000:5002"
    volumes:
      - mlflow_data:/mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://0.0.0.0:5002/"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s

  cookbot:
    profiles: ["cookbot"]
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cookbot
    container_name: cookbot
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - mlflow_data:/mlflow
    depends_on:
      mlflow:
        condition: service_healthy
    tty: true
    stdin_open: true
    command: ["python", "src/main.py"]

  gptbot-api:
    profiles: ["gptbot"]
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gptbot
    container_name: gptbot_api
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://0.0.0.0:8000/health"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s

  gptbot:
    profiles: ["gptbot"]
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gptbot
    container_name: gptbot_chat
    depends_on:
      gptbot-api:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      - HOST_NUMBER=gptbot-api
    command: ["python", "interactive_chat.py"]

volumes:
  mlflow_data: