########################################
# cookbot Deployment
########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbot
  template:
    metadata:
      labels:
        app: cookbot
    spec:
      containers:
        - name: cookbot
          image: cookbot:local
          command: ["python", "src/main.py"]
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: cookbot-env
---
########################################
# cookbot Service
########################################
apiVersion: v1
kind: Service
metadata:
  name: cookbot
spec:
  selector:
    app: cookbot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
########################################
# gptbot-api Deployment
########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gptbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gptbot-api
  template:
    metadata:
      labels:
        app: gptbot-api
    spec:
      containers:
        - name: gptbot-api
          image: gptbot:local
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          tty: true
          stdin: true
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
---
########################################
# gptbot-api Service
########################################
apiVersion: v1
kind: Service
metadata:
  name: gptbot-api
spec:
  selector:
    app: gptbot-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
########################################
# gptbot Deployment
########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gptbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gptbot
  template:
    metadata:
      labels:
        app: gptbot
    spec:
      containers:
        - name: gptbot
          image: gptbot:local
          command: ["python", "interactive_chat.py"]
          tty: true
          stdin: true
          ports:
            - containerPort: 5000
              name: chat
          env:
            - name: HOST_NUMBER
              value: "gptbot-api"
---
########################################
# gptbot Service
########################################
apiVersion: v1
kind: Service
metadata:
  name: gptbot
spec:
  selector:
    app: gptbot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
